### ISSUE TITLE
Conflict with modernizr

### ISSUE THREAD

**Issue by andrey-hohlov** [olegskl/gulp-stylelint#71]
Hello!

**package.json dependencies**

```
"devDependencies": {
  "gulp": "^3.9.1",
  "gulp-stylelint": "^3.8.0"
},
"dependencies": {
  "modernizr": "^3.3.1"
}
```

**gulpfile**
``` javascript
const gulp = require('gulp');

gulp.task('lint-css', function lintCssTask() {
  const gulpStylelint = require('gulp-stylelint');
  return gulp
    .src('style.css')
    .pipe(gulpStylelint({
    reporters: [
      {formatter: 'string', console: true}
    ]
  }));
});
```

1. Run `npm i` for install dependencies
2. Run `gulp lint-css`
3. Get error!

```
[16:32:31] Starting 'lint-css'...
[16:32:31] 'lint-css' errored after 795 ms
[16:32:31] TypeError in plugin 'gulp-stylelint'
Message:
    Cannot read property '0' of undefined
```

I have added `debug: true` and see that:

```
TypeError: Cannot read property '0' of undefined
    at _.omitBy (/Users/andrey/Work/Repositories/test/node_modules/stylelint/lib/formatters/jsonFormatter.js:8:48)
    at /Users/andrey/Work/Repositories/test/node_modules/lodash/lodash.js:11233:17
    at /Users/andrey/Work/Repositories/test/node_modules/lodash/lodash.js:3085:13
    at /Users/andrey/Work/Repositories/test/node_modules/lodash/lodash.js:3925:15
    at baseForIn (/Users/andrey/Work/Repositories/test/node_modules/lodash/lodash.js:2509:40)
    at basePickBy (/Users/andrey/Work/Repositories/test/node_modules/lodash/lodash.js:3084:7)
    at Function.omitBy (/Users/andrey/Work/Repositories/test/node_modules/lodash/lodash.js:11232:14)
    at results.map.result (/Users/andrey/Work/Repositories/test/node_modules/stylelint/lib/formatters/jsonFormatter.js:8:14)
    at Array.map (native)
    at module.exports (/Users/andrey/Work/Repositories/test/node_modules/stylelint/lib/formatters/jsonFormatter.js:7:34)
```

Also:
1. stylelintrc - no matter
2. Error only if css file exist

**How it works:**

1. Run `npm i gulp gulp-stylelint modernizr` instead of `npm i`
2. Run `gulp lint-css`
3. Works!

It depends on order of packages installing!

Node v6.2.1
NPM 3.10.6
MacOS 10.12.2

**Comment by olegskl** [comment]
Hello, I'm able to reproduce this. However, I'd rather open an issue at stylelint's repository seeing that the error originates in the stylelint formatter. The `_.omitBy` function used in jsonFormatter takes only two arguments, not three...
